const projects=[
["Rivilog Pickup","Sistema web para planejamento, execução e monitoramento de coletas, com validação geográfica, auditoria, mapas e notificações.","Next.js 16 • React 19 • TypeScript • PostgreSQL"],
["Rivilog Pedágios","Plataforma para registro de despesas de pedágio, envio de comprovantes e extratos, protocolos, painel administrativo e exportações.","Next.js 16 • TypeScript • Supabase • Vercel"],
["Gerador de Contratos","Sistema para criação, assinatura e acompanhamento de contratos, compartilhamento por link temporário e organização de agendamentos.","Python • Flask • PostgreSQL • Segurança"],
["Visualizador de Holerites","Solução desenvolvida para facilitar a consulta e visualização organizada de holerites.","Sistema Web • Documentos • Consulta"],
["Sistema de Gestão L&H","Sistema privado que centraliza processos administrativos, financeiros, contratuais, faturamento, recebimentos e documentos.","Python • Flask • PostgreSQL • Cloudflare R2"],
["IC TECH","Plataforma acadêmica voltada ao gerenciamento ágil de equipes e organização de atividades com práticas de Scrum e Kanban.","Desenvolvimento Web • Scrum • Kanban"]
];
const certs=[["Excel Completo","80h"],["Web 3.0","20h"],["Fundamentos da Inteligência Artificial","8h"],["Privacidade e Proteção de Dados (LGPD)","4h"],["Desvendando a Indústria 4.0","20h"],["Desvendando o ESG","20h"],["Economia Circular","20h"],["Empreender SENAI","20h"],["Segurança no Trabalho","14h"],["Desvendando o 5G","15h"]];
export default function Home(){return <main>
<nav><b>NR.</b><div><a href="#historia">História</a><a href="#projetos">Projetos</a><a href="#formacao">Formação</a><a href="#certificados">Certificados</a></div></nav>
<section className="hero"><div><span className="eyebrow">DESENVOLVEDOR DE SISTEMAS</span><h1>Nicolas Ricardo<br/><em>transforma ideias em sistemas.</em></h1><p>Desenvolvedor, técnico em Desenvolvimento de Sistemas e estudante de Análise e Desenvolvimento de Sistemas. Construo soluções para problemas reais, unindo tecnologia, organização e aprendizado contínuo.</p><div className="actions"><a className="primary" href="#projetos">Conheça meus projetos</a><a href="https://github.com/Nicolas1xx">GitHub ↗</a></div></div><div className="portrait"><div className="photoPlaceholder">NR</div><small>Foto profissional será adicionada na próxima atualização</small></div></section>
<section id="historia" className="story"><span className="eyebrow">MINHA TRAJETÓRIA</span><h2>Da escola pública ao desenvolvimento de soluções reais.</h2><div className="storygrid"><p>Grande parte da minha trajetória escolar aconteceu no <strong>ensino público</strong>. Foi nesse caminho que desenvolvi curiosidade por tecnologia e a vontade de aprender além da sala de aula. A educação se tornou a base para transformar interesse em conhecimento técnico e, depois, em projetos concretos.</p><p>Avancei para o <strong>Ensino Médio no SESI</strong> junto à formação de <strong>Técnico em Desenvolvimento de Sistemas pelo SENAI</strong>. Nesse período, programação deixou de ser apenas interesse e passou a ser uma área profissional: banco de dados, desenvolvimento web, redes, lógica e construção de sistemas.</p><p>Hoje curso <strong>Análise e Desenvolvimento de Sistemas no SENAI</strong> e continuo evoluindo por meio de projetos acadêmicos, iniciação científica e sistemas utilizados em situações reais. Minha trajetória é marcada por prática: identificar um problema, entender o processo e construir uma solução que realmente possa ser utilizada.</p></div></section>
<section id="projetos"><span className="eyebrow">PORTFÓLIO</span><h2>Projetos em destaque</h2><div className="grid">{projects.map((p,i)=><article key={p[0]}><span>0{i+1}</span><h3>{p[0]}</h3><p>{p[1]}</p><small>{p[2]}</small></article>)}</div></section>
<section id="formacao" className="dark"><span className="eyebrow">FORMAÇÃO</span><h2>Conhecimento construído na prática.</h2><div className="timeline"><div><b>Atual</b><h3>Análise e Desenvolvimento de Sistemas</h3><p>SENAI • Graduação</p></div><div><b>Concluído</b><h3>Técnico em Desenvolvimento de Sistemas</h3><p>SENAI Luiz Pagliato • Formação técnica</p></div><div><b>Concluído</b><h3>Ensino Médio</h3><p>SESI</p></div></div><h3 className="skilltitle">Tecnologias & competências</h3><div className="tags">{["React","Next.js","TypeScript","JavaScript","Python","Flask","Java","MySQL","PostgreSQL","Supabase","Firebase","MongoDB","Git","APIs","Desenvolvimento Web","Banco de Dados"].map(x=><span key={x}>{x}</span>)}</div></section>
<section id="certificados"><span className="eyebrow">FORMAÇÃO COMPLEMENTAR</span><h2>Certificações SENAI</h2><div className="certs">{certs.map(c=><div key={c[0]}><b>{c[0]}</b><span>SENAI • {c[1]}</span></div>)}</div></section>
<footer><h2>Vamos construir algo?</h2><p>Projetos, tecnologia e desenvolvimento de soluções.</p><div><a href="https://github.com/Nicolas1xx">GitHub</a><a href="https://www.linkedin.com/in/nicolas-ricardo-a95741307">LinkedIn</a></div><small>© 2026 Nicolas Ricardo</small></footer>
</main>}