"use client";
import {useEffect,useState} from "react";
import profilePhoto from "./nicolas.jpg";

type Project={name:string;summary:string;stack:string;problem:string;development:string;features:string[];architecture:string};
const projects:Project[]=[
{name:"Health & Leão e Kourani Software",summary:"ERP interno para gestão financeira, contratos, RH, pagamentos, faturamento, recebimentos, documentos e indicadores.",stack:"Python • Flask • PostgreSQL • Cloudflare R2",problem:"Centralizar processos administrativos, financeiros e contratuais que antes precisavam ser acompanhados em diferentes rotinas.",development:"Desenvolvido como uma aplicação privada em Flask, concentrando autenticação, regras administrativas e interfaces. A persistência utiliza SQLAlchemy com PostgreSQL em produção, enquanto documentos e anexos podem ser mantidos em armazenamento privado compatível com S3.",features:["Controle de usuários, cargos e permissões","Gestão e geração de contratos","Faturamento, recebimentos e controle financeiro","Relatórios, documentos e anexos","Rotinas de backup, migração e verificação"],architecture:"Backend Flask + SQLAlchemy, PostgreSQL para dados estruturados, Cloudflare R2 para anexos privados e Render para implantação."},
{name:"Rivilog Pedágios",summary:"Sistema para registro e gestão de despesas de pedágio, envio de comprovantes e extratos, protocolos, painel administrativo e exportações.",stack:"Next.js 16 • TypeScript • Supabase • Vercel",problem:"Organizar o envio, conferência e acompanhamento de despesas e comprovantes de pedágio em um fluxo único.",development:"A interface Next.js coleta e valida os dados. Os registros são persistidos no Supabase e os comprovantes e extratos são enviados ao Storage. Rotas server-side cuidam de integrações como a confirmação por e-mail.",features:["Formulário guiado de despesas","Upload de múltiplos comprovantes e extrato PDF","Geração de protocolo e confirmação por e-mail","Painel com pesquisa e filtros","Exportação em Excel e ZIP"],architecture:"Next.js App Router no frontend e servidor, Supabase Database + Storage, Resend para e-mail e Vercel para hospedagem."},
{name:"Rivilog Pickup",summary:"Sistema web para planejamento, execução e monitoramento de coletas, com validação geográfica, auditoria, mapas e notificações.",stack:"Next.js 16 • React 19 • TypeScript • PostgreSQL",problem:"Dar controle operacional às coletas, permitindo planejar rotas, acompanhar execução e validar a baixa no local correto.",development:"Construído com Next.js App Router, React e TypeScript. As regras críticas são executadas no servidor e os dados ficam em PostgreSQL. A aplicação utiliza geolocalização, mapa, controle de acesso por perfil e uma fila persistida para notificações.",features:["Cadastro de clientes, lojas, motoristas e veículos","Rotas, paradas e monitoramento de progresso","Validação por GPS e raio geográfico","Auditoria e liberação manual de exceções","Notificações via WhatsApp quando configuradas"],architecture:"Next.js server-side + PostgreSQL/Drizzle, mapas OpenStreetMap, BrasilAPI para CEP e WhatsApp Cloud API para notificações."},
{name:"Gerador de Contratos",summary:"Sistema para criação, assinatura e acompanhamento de contratos, compartilhamento por link temporário e organização de agendamentos.",stack:"Python • Flask • PostgreSQL • Segurança",problem:"Centralizar a elaboração, compartilhamento, assinatura e acompanhamento administrativo de contratos.",development:"A aplicação usa Flask e Jinja. O backend aplica autenticação, validações, proteção CSRF, limitação de requisições e criptografia de dados pessoais. Os documentos são gerados em Word e links temporários permitem o fluxo de assinatura.",features:["Criação e validação de contratos","Geração de documentos Word","Links temporários e assinatura única","Agenda com filtros e prevenção de conflitos","Histórico de eventos e exclusão lógica"],architecture:"Flask/Jinja no servidor, PostgreSQL em produção, python-docx para documentos e Cryptography para proteção de dados."},
{name:"Visualizador de Holerites",summary:"Solução desenvolvida para facilitar a consulta e visualização organizada de holerites.",stack:"Sistema Web • Documentos • Consulta",problem:"Facilitar o acesso e a organização de holerites em uma interface de consulta.",development:"Este projeto será detalhado no portfólio conforme a documentação técnica correspondente for identificada no repositório. A descrição atual evita atribuir tecnologias ou funcionalidades não confirmadas.",features:["Consulta organizada de holerites","Visualização centralizada de documentos"],architecture:"Arquitetura técnica não identificada na documentação pesquisada até o momento."},
{name:"IC TECH",summary:"Plataforma acadêmica voltada ao gerenciamento ágil de equipes e organização de atividades com práticas de Scrum e Kanban.",stack:"Desenvolvimento Web • Scrum • Kanban",problem:"Apoiar a organização de equipes acadêmicas e o acompanhamento de atividades utilizando práticas ágeis.",development:"Projeto de iniciação científica desenvolvido como plataforma web, evoluindo por etapas de levantamento de requisitos, arquitetura, front-end, quadro Kanban, integrações, testes e validação.",features:["Organização de equipes acadêmicas","Quadro Kanban","Acompanhamento de atividades","Aplicação de práticas Scrum","Evolução orientada por testes e feedback"],architecture:"Plataforma web estruturada a partir de requisitos e arquitetura definidos no projeto de iniciação científica."}
];
const certs=[["Excel Completo","80h"],["Web 3.0","20h"],["Fundamentos da Inteligência Artificial","8h"],["Privacidade e Proteção de Dados (LGPD)","4h"],["Desvendando a Indústria 4.0","20h"],["Desvendando o ESG","20h"],["Economia Circular","20h"],["Empreender SENAI","20h"],["Segurança no Trabalho","14h"],["Desvendando o 5G","15h"]];

export default function Home(){
 const [selected,setSelected]=useState<Project|null>(null);
 useEffect(()=>{document.body.style.overflow=selected?"hidden":"";return()=>{document.body.style.overflow=""}},[selected]);
 return <main>
<nav><b>NR.</b><div><a href="#historia">História</a><a href="#projetos">Projetos</a><a href="#formacao">Formação</a><a href="#certificados">Certificados</a></div></nav>
<section className="hero"><div><span className="eyebrow">DESENVOLVEDOR DE SISTEMAS</span><h1>Nicolas Ricardo<br/><em>transforma ideias em sistemas.</em></h1><p>Desenvolvedor, técnico em Desenvolvimento de Sistemas e estudante de Análise e Desenvolvimento de Sistemas. Construo soluções para problemas reais, unindo tecnologia, organização e aprendizado contínuo.</p><div className="actions"><a className="primary" href="#projetos">Conheça meus projetos</a><a href="https://github.com/Nicolas1xx">GitHub ↗</a></div></div><div className="portrait"><img className="profilePhoto" src={profilePhoto.src} alt="Nicolas Ricardo" /><small>Nicolas Ricardo • Desenvolvedor de Sistemas</small></div></section>
<section id="historia" className="story"><span className="eyebrow">MINHA TRAJETÓRIA</span><h2>Da escola pública ao desenvolvimento de soluções reais.</h2><div className="storygrid"><p>Grande parte da minha trajetória escolar aconteceu no <strong>ensino público</strong>. Foi nesse caminho que desenvolvi curiosidade por tecnologia e a vontade de aprender além da sala de aula. A educação se tornou a base para transformar interesse em conhecimento técnico e, depois, em projetos concretos.</p><p>Avancei para o <strong>Ensino Médio no SESI</strong> junto à formação de <strong>Técnico em Desenvolvimento de Sistemas pelo SENAI</strong>. Nesse período, programação deixou de ser apenas interesse e passou a ser uma área profissional: banco de dados, desenvolvimento web, redes, lógica e construção de sistemas.</p><p>Hoje curso <strong>Análise e Desenvolvimento de Sistemas no SENAI</strong> e continuo evoluindo por meio de projetos acadêmicos, iniciação científica e sistemas utilizados em situações reais. Minha trajetória é marcada por prática: identificar um problema, entender o processo e construir uma solução que realmente possa ser utilizada.</p></div></section>
<section id="projetos"><span className="eyebrow">PORTFÓLIO</span><h2>Projetos em destaque</h2><p className="projectHint">Passe o mouse para explorar • clique para ver o projeto completo</p><div className="grid">{projects.map((p,i)=><button className="projectCard" key={p.name} onClick={()=>setSelected(p)}><span>0{i+1}</span><h3>{p.name}</h3><p>{p.summary}</p><small>{p.stack}</small><strong className="viewProject">VER DETALHES →</strong></button>)}</div></section>
<section id="formacao" className="dark"><span className="eyebrow">FORMAÇÃO</span><h2>Conhecimento construído na prática.</h2><div className="timeline"><div><b>Atual</b><h3>Análise e Desenvolvimento de Sistemas</h3><p>SENAI • Graduação</p></div><div><b>Concluído</b><h3>Técnico em Desenvolvimento de Sistemas</h3><p>SENAI Luiz Pagliato • Formação técnica</p></div><div><b>Concluído</b><h3>Ensino Médio</h3><p>SESI</p></div></div><h3 className="skilltitle">Tecnologias & competências</h3><div className="tags">{["React","Next.js","TypeScript","JavaScript","Python","Flask","Java","MySQL","PostgreSQL","Supabase","Firebase","MongoDB","Git","APIs","Desenvolvimento Web","Banco de Dados"].map(x=><span key={x}>{x}</span>)}</div></section>
<section id="certificados"><span className="eyebrow">FORMAÇÃO COMPLEMENTAR</span><h2>Certificações SENAI</h2><div className="certs">{certs.map(c=><div key={c[0]}><b>{c[0]}</b><span>SENAI • {c[1]}</span></div>)}</div></section>
<footer><div className="footerTop"><div><span className="footerEyebrow">CONTATO</span><h2>Tem uma ideia ou um desafio?<br/><em>Vamos transformar em solução.</em></h2><p>Estou sempre aberto a novos projetos, oportunidades e conversas sobre tecnologia. Se você procura alguém que goste de entender problemas e construir soluções que realmente funcionem, fale comigo.</p></div><div className="footerActions"><a className="footerPrimary" href="https://www.linkedin.com/in/nicolas-ricardo-a95741307" target="_blank" rel="noreferrer">Falar comigo no LinkedIn <span>↗</span></a><a className="footerSecondary" href="https://github.com/Nicolas1xx" target="_blank" rel="noreferrer">Explorar meu GitHub <span>↗</span></a></div></div><div className="footerBottom"><div><b>NR.</b><span>Nicolas Ricardo Kourani Leão Silva</span></div><span>Desenvolvedor de Sistemas • © 2026</span></div></footer>
{selected&&<div className="modalBackdrop" onMouseDown={()=>setSelected(null)}><div className="projectModal" role="dialog" aria-modal="true" aria-label={selected.name} onMouseDown={e=>e.stopPropagation()}><button className="closeModal" onClick={()=>setSelected(null)} aria-label="Fechar">×</button><span className="eyebrow">PROJETO EM DETALHES</span><h2>{selected.name}</h2><p className="modalLead">{selected.summary}</p><div className="modalStack">{selected.stack}</div><div className="detailGrid"><div><h3>O desafio</h3><p>{selected.problem}</p></div><div><h3>Como foi desenvolvido</h3><p>{selected.development}</p></div><div><h3>Principais funcionalidades</h3><ul>{selected.features.map(f=><li key={f}>{f}</li>)}</ul></div><div><h3>Arquitetura</h3><p>{selected.architecture}</p></div></div></div></div>}
</main>}